"""
Paper content for MR.AsyncFL, organized by section.
Used for RAG chunking and embedding.
Math is written in readable notation rather than LaTeX.
"""

PAPER_TITLE = "MR.AsyncFL: Staleness-Aware Aggregation for Asynchronous Federated Learning via Model Replacement"

PAPER_ABSTRACT = """
MR.AsyncFL: Staleness-Aware Aggregation for Asynchronous Federated Learning via Model Replacement

ABSTRACT

Asynchronous federated learning (AFL) has become increasingly popular and crucial for scalable, privacy-preserving machine learning across diverse and distributed edge devices. However, a fundamental challenge in FL is the staleness of client updates, which can degrade global model accuracy and slow down convergence as clients operate and communicate independently. Existing AFL methods typically address this issue by down-weighting stale updates, but outdated client information may still persist in the global model over time. In this paper, we propose MR.AsyncFL, a fully AFL framework based on model replacement. Upon receiving a new local model from a client, the server replaces that client's previously cached contribution in the global model with the updated one, preserving the invariant that the global model remains a convex combination of the most recent available client models. To support this mechanism, we propose a recursive weight update scheme that preserves normalization in a lightweight and fully asynchronous manner. We further provide a convergence analysis for MR.AsyncFL under bounded staleness and client participation assumptions, and derive an O(T^{-1/4}) convergence rate under a specific parameter scaling. Experiments on CIFAR-10 and CIFAR-100 under both IID and non-IID settings, with and without staleness thresholds, show that MR.AsyncFL consistently outperforms representative asynchronous baselines, such as FedAsync, TWAFL, and Rolling FedAvg, while maintaining strong robustness under severe staleness and system heterogeneity.
"""

PAPER_INTRODUCTION = """
SECTION 1: INTRODUCTION

Massive amounts of data are continually generated by various devices, sensors and mobile applications across the Internet. Privacy regulations and rising public concern about data misuse have made it untenable to centralize sensitive data. Federated learning (FL) has emerged as a promising solution that trains machine learning models collaboratively across a network of clients while keeping raw data local. By exchanging only model updates instead of raw data, FL mitigates privacy leakage and reduces communication burden. This privacy-preserving paradigm has already seen wide adoption in sensitive domains such as smart-healthcare systems and autonomous driving applications where personal data must not be disclosed.

As FL scales to larger and more diverse networks of mobile phones, edge devices and organizational silos, the underlying infrastructure becomes highly heterogeneous. Clients vary widely in computation power, storage, energy consumption and connectivity. Their datasets are often non-IID (non-independently and identically distributed).

Most FL algorithms adopt a synchronous federated learning (SFL) framework, such as FedAvg, in which the server broadcasts a global model, selected clients perform local training, and the server waits for all selected clients to upload their updates before aggregation. In synchronous systems, clients with limited computing power, unstable connectivity, or temporary unavailability become stragglers. Since the server cannot proceed to the next round until updates from all selected clients are received, these slower or offline clients delay the entire training cycle. Consequently, faster clients remain idle, and overall training speed is constrained by the slowest participant, resulting in poor resource utilization and prolonged training times.

Asynchronous federated learning (AFL) addresses this bottleneck by eliminating strict synchronization at the aggregation stage. Rather than waiting for all selected clients, the server updates the global model upon receiving each client update, thereby preventing stragglers from delaying system-wide progress. By decoupling client updates from strict synchronization, AFL drastically reduces waiting time and better utilizes available client resources.

However, the flexibility of AFL introduces a fundamental challenge: staleness. Because local training on clients and global aggregations on the server occur independently, slow clients may have been training for a long period using an outdated global model that had been updated multiple times by faster clients. The server may receive updates computed from stale models. Aggregating such outdated gradients can destabilize training, introduce inconsistent model updates, and degrade final accuracy.

The timing of aggregation introduces a trade-off in client model staleness. Fully AFL can accelerate global model convergence by immediately incorporating updates, but it increases staleness, which may amplify training bias and risk divergence. In contrast, SFL eliminates staleness by waiting for all selected clients before aggregation, but improves consistency at the cost of lower resource utilization and longer overall training time.

Designing aggregation algorithms that can robustly handle staleness is therefore a central challenge in asynchronous federated optimization. To address this challenge, we introduce MR.AsyncFL, an asynchronous federated learning framework based on model replacement.

Main contributions of MR.AsyncFL:
1. We propose MR.AsyncFL, a novel AFL framework that introduces a stale-model substitution paradigm for asynchronous aggregation. In contrast to existing asynchronous methods that mainly attenuate stale updates through temporal decay or staleness-aware weighting (FedAsync, TWAFL, WKAFL), MR.AsyncFL uses each newly uploaded local model in two ways: first, it replaces the same client's previously cached stale contribution, and second, it participates in the aggregation step that produces the next global model. This design reduces the lingering effect of outdated information and helps mitigate staleness-induced drift over time.

2. We design a recursive weight normalization scheme that dynamically adjusts each client's contribution based on its update delay and participation history. The proposed scheme maintains normalization without requiring additional buffers or optimizer-specific modifications, enabling stable and efficient integration of stale-model replacement in fully asynchronous settings.

3. We establish a convergence guarantee for MR.AsyncFL and show that it achieves an O(T^{-1/4}) convergence rate under certain assumptions.

4. We conduct extensive experiments on benchmark datasets under both IID and non-IID settings, with and without staleness-threshold mechanisms. The results demonstrate that MR.AsyncFL consistently achieves faster convergence and higher accuracy compared to representative asynchronous FL baselines, validating both the effectiveness and practical advantages of the proposed framework.
"""

PAPER_RELATED_WORK = """
SECTION 2: RELATED WORK

2.1 Staleness-Aware AFL via Weight Aggregation

FedAsync proposed an asynchronous optimization scheme in which the server performs an immediate aggregation upon the arrival of an update from a client. To mitigate staleness, their method applied a staleness-aware hyperparameter during aggregation, blending the previous global model with the new local update using a simple weighting mechanism. However, its treatment of staleness remains coarse, since stale updates are only softened through weighting rather than being explicitly corrected or removed.

TWAFL applied time-decay functions with exponential decay to the aggregation update rule to deal with the staleness issue.

WKAFL went further with a two-stage K-async design that selects gradients with consistent descent directions, clips large-norm gradients, and adjusts the learning rate according to the least staleness. WKAFL combines exponential staleness weighting and momentum to improve robustness on non-IID data. The drawback is added algorithmic complexity and tuning burden.

FedACA adopts an "informative update" policy in which a client sends updates only when its model has changed significantly and the server weights update by a time-related factor. This can reduce unnecessary communication and prioritize more meaningful updates, but its effectiveness depends on the quality of the triggering criterion and it still relies on weighting-based handling of delayed information.

TimelyFL addresses fairness through wall-clock time control and adaptive workload assignment, enabling slower devices to participate more regularly. While this improves inclusiveness, its focus is primarily on participation fairness rather than directly resolving the fundamental effect of stale updates.

Overall, these methods largely remain within a weighted-aggregation framework, where stale information is moderated rather than explicitly replaced or removed.

2.2 Staleness-Aware AFL via Client Selection

A growing body of research addresses the staleness issue by intelligently controlling which clients are selected to participate in each round.

A semi-asynchronous protocol proposed by Hao et al. allows a selected subset of clients to upload their updates as soon as they finish local training. To mitigate straggler effects, the server maintains a priority-based selection policy that favors clients with larger datasets and higher computing power, while a GAN-based data expansion module is used to balance data volume between clients.

TEA-Fed is a hybrid AFL protocol that allows idle clients to proactively apply for training, with a server-side C-fraction control to limit participation. To handle staleness, TEA-Fed incorporates a staleness-aware weighted aggregation scheme and caches multiple versions of the global model for alignment.

FLACOS formulates client selection in AFL as a multi-armed bandit (MAB) problem with fairness constraints. The algorithm combines an upper-confidence-bound (UCB) policy with a virtual queue mechanism to ensure that frequently overlooked clients are eventually selected, balancing training speed and long-term fairness.

For heterogeneous IoT environments, Chen et al. propose a lightweight node-selection strategy that considers each client's real-time availability and resource conditions. By deferring low-quality updates and prioritizing reliable contributors, their approach improves convergence without requiring synchronization.

An asynchronous learning-aware scheduling (ALS) problem formulation introduces an effectivity score that penalizes outdated updates while rewarding fresh contributions. Using this score, dynamic scheduling policies are designed using reinforcement learning and dynamic programming.

Overall, client selection methods address staleness indirectly by controlling which updates are generated and transmitted. Most do not directly correct the effect of stale updates once those updates have already entered the aggregation process. As a result, they are best viewed as complementary to, rather than replacements for, server-side staleness-handling mechanisms.
"""

PAPER_ALGORITHM = """
SECTION 3: MR.AsyncFL - ASYNCHRONOUS FEDERATED LEARNING WITH MODEL REPLACEMENT

3.1 Problem Setup

We consider an AFL system consisting of a central server and N clients indexed by i in {1,...,N}. Each client i possesses a private local dataset of size n_i sampled from its local data distribution D_i. The local data is never shared outside the device. The central server maintains a global model w in R^d.

The objective is to collaboratively learn a global model that minimizes the weighted loss across all clients:

    minimize F(w) = sum_{i=1}^{N} r_i * F_i(w)

where r_i = n_i / (sum_{j=1}^{N} n_j) denotes the relative data size of client i, F_i(w) = E_{zeta ~ D_i}[f(w; zeta)] is the expected loss over client i's local data distribution, and f(w, zeta) is the loss function for model w on a sample data zeta.

3.2 System Overview and Communication Protocol

MR.AsyncFL follows the standard AFL protocol, similar to FedAsync, where clients communicate with the server independently upon completing their local updates.

Protocol Steps:
1. SYSTEM INITIATION: The server broadcasts the initial global model w_0^g to a list of selected clients, who start a round of training using their local data and this global model.

2. CLIENT-SIDE (LOCAL) UPDATE: After client i performs local training on its private dataset using stochastic gradient descent (one gradient step for clarity), the updated local model is uploaded to the server. The local model after training is:
   w_t^(i) = w_{t-delta_t-1}^g - eta * g_t
   where eta > 0 is the step-size, g_t is a local gradient, and delta_t >= 0 denotes the staleness. The model may be trained from an earlier round t-delta_t-1 instead of the last round t-1.

3. MODEL EXCHANGE: Upon receiving client i's model w_t^(i), the server enters round t and immediately broadcasts its latest aggregated global model w_{t-1}^g to client i before executing the stale model replacement and aggregation step. This is the pre-aggregation design (as opposed to post-aggregation where the client receives the newly updated model).

4. SERVER-SIDE (GLOBAL) AGGREGATION: After sending the global model to client i, the server integrates w_t^(i) into the global model using the proposed update rule.

For theoretical analysis, we assume staleness is bounded: delta_t <= tau for some constant tau > 0. If a client has not uploaded to the server for more than tau rounds, the server will reset its training by sending the most recent available global model. This bounded-staleness mechanism is commonly adopted in AFL to limit adverse effects of severely outdated models.

FedAsync update rule for comparison:
    w_t^g = gamma * w_{t-1}^g + (1-gamma) * w_t^(i)
where gamma in (0,1) is the mixing coefficient.

3.3 Client Contribution and Global Update

At any round t > 0, the server-side global model can be viewed as a cached mixture:
    w_{t-1}^g = sum_{j=1}^{N} c_{t-1}^(j) * w_{t-1}^(j)

where c_{t-1}^(j) >= 0 denotes the coefficient assigned to client j, and w_{t-1}^(j) denotes the most recent cached local model from client j on the server. The client weight c_{t-1}^(j) satisfies sum_{j=1}^{N} c_{t-1}^(j) = 1 throughout training.

For the communicating client i, the cached stale model corresponds to w_{t-delta_t}^(i).

The stale-model replacement step:
    w_tilde_{t-1}^g = w_{t-1}^g - c_{t-1}^(i) * w_{t-delta_t}^(i) + c_{t-1}^(i) * w_t^(i)

MR.AsyncFL Update Equation:
    w_t^g = gamma * w_tilde_{t-1}^g + (1-gamma) * w_t^(i)
          = gamma * w_{t-1}^g + (1-gamma) * w_t^(i) + gamma * c_{t-1}^(i) * (w_t^(i) - w_{t-delta_t}^(i))
          = sum_{j!=i} gamma * c_{t-1}^(j) * w_{t-1}^(j) + (gamma * c_{t-1}^(i) + 1-gamma) * w_t^(i)

The additional term gamma * c_{t-1}^(i) * (w_t^(i) - w_{t-delta_t}^(i)) is the key difference from FedAsync. This term removes the old stale contribution of client i completely.

In FedAsync, expanding the update shows:
    w_t^g = sum_{j!=i} gamma * c_{t-1}^(j) * w_{t-1}^(j) + gamma * c_{t-1}^(i) * w_{t-delta_t}^(i) + (1-gamma) * w_t^(i)
The stale contribution gamma * c_{t-1}^(i) * w_{t-delta_t}^(i) remains after the update. In MR.AsyncFL, this is explicitly removed.

Recursive Weight Update:
The updated weights after incorporating w_t^(i):
    c_t^(j) = gamma * c_{t-1}^(j),              for j != i (non-participating)
    c_t^(i) = gamma * c_{t-1}^(i) + (1-gamma),  for j = i  (participating)

Initial values: c_0^(j) = 1/N for all j.

Interpretation: Non-participating clients have their importance discounted by gamma (they are one step staler). The participating client i is first discounted by gamma but also receives a bonus (1-gamma) due to its recency.

Normalization property: Given sum_{j=1}^{N} c_{t-1}^(j) = 1, we have:
    sum_{j=1}^{N} c_t^(j) = gamma * sum_{j=1}^{N} c_{t-1}^(j) + (1-gamma) = 1

This guarantees the global model remains a convex combination of cached client models.

Memory cost: MR.AsyncFL requires storing the previous local model for each client. In practice, this can be mitigated using compressed (low-precision) models or by grouping clients into representative clusters.

3.4 Algorithm Summary

At each communication event, the server:
1. Retrieves the previously stored local model w_{t-delta_t}^(i) for client i
2. Updates global model w_t^g using the MR.AsyncFL update equation
3. Updates weights c_t^(i) and c_t^(j) for j != i using the recursive rule
4. Stores w_t^(i) as the latest model from client i

Both clients and the server proceed independently. Clients update at their own pace and the server integrates incoming updates immediately upon arrival. The recursive weighting scheme naturally balances client contributions over time.
"""

PAPER_CONVERGENCE = """
SECTION 4: CONVERGENCE ANALYSIS

Assumptions:

Assumption 1 (Objective Properties): The global objective F: R^d -> R is bounded from below (F(w) >= F* for all w) and L-smooth: ||nabla F(u) - nabla F(v)|| <= L * ||u - v|| for all u, v.

Assumption 2 (Stochastic Gradient): With filtration {F_t}_{t>=0}, the realized client update satisfies:
    g_t = nabla F_i(w^g_{t-delta_t-1}) + xi_t,   E[xi_t | F_{t-1}] = 0
where xi_t is zero-mean noise.

Assumption 3 (Bounded Staleness): The staleness is bounded by delta_t <= tau where tau > 0 is a finite positive integer.

Assumption 4 (Participation Probability): The participation probability of client i is r_i. The maximum of these probabilities is bounded by r in [1/N, 1). Using 1_t^i in {0,1} to indicate whether client i participates in round t, we have r_i = E[1_t^i] <= r for all i, t.

Assumption 5 (Bounded Local Update): For any client and t, the local gradient update is bounded: ||g_t|| <= G.

Assumption 6 (rho condition): The discount factor gamma and participation bound r satisfy:
    rho := 4 * tau^2 * [(1-gamma)^2 + gamma^2 * r] < 1.
This assumption ensures a contraction property in the proof.

Key Lemmas:

Lemma 1 (Bound for Client Weight): Under Assumption 4, the expected client weight is bounded:
    E[c_t^(i)] <= r  and  E[(c_t^(i))^2] <= r.

Lemma 2 (Bound for Term B): Under Assumptions 3-6, we have:
    (1/T) * sum_{t=1}^{T} E[||Delta_t||^2] <= C_Delta * eta^2
where C_Delta = 4 * G^2 * [(1-gamma)^2 + 2*gamma*r] / (1-rho) > 0,
and Delta_t = w_t^g - w_{t-1}^g is the global model update at round t.

Corollary (Bound on Average Global Drift): Under the same assumptions as Lemma 2:
    (1/T) * sum_{t=1}^{T} E[||w^g_{t-1} - w^g_{t-delta_t-1}||^2] = C_w * eta^2
where C_w = tau^2 * C_Delta.

Lemma 3 (Bound for Term A): Under Assumptions 1-6, we have:
    (1/T) * sum_{t=1}^{T} E[<nabla F(w_{t-1}^g), Delta_t>]
    <= [(1-gamma + 2*gamma*r)/eta + eta*L^2] * C_w/T + eta*gamma*r*G^2
       - (eta*(1-gamma)/4T) * sum_{t=1}^{T} E[||nabla F(w_{t-1}^g)||^2]

Main Convergence Theorem: Under Assumptions 1-6:
    min_{t=1,...,T} E[||nabla F(w_{t-1}^g)||^2]
    <= (4/(1-gamma)) * (
          (F(w_0^g) - F*) / (eta*T)
          + C_w * [(1-gamma+2*gamma*r)/2 + eta^2*L^2]
          + gamma*r*G^2
          + L*C_Delta*eta
       )

O(T^{-1/4}) Rate: By choosing:
    eta = 1/sqrt(T),  r = 2/N,  gamma = 1 - 1/T^{1/4},  T = N^2

we obtain a convergence rate of O(T^{-1/4}).

This scaling means: with reasonable participation (r = 2/N) and sufficient training (T = N^2 rounds), the minimum expected gradient norm decays at rate O(T^{-1/4}). As the client population N grows with the training horizon T, the residual error floor vanishes naturally.

Comparison to FedAsync Convergence:
Both proofs contain a non-vanishing residual term caused by asynchrony and staleness. In MR.AsyncFL, this error floor is driven to zero by choosing r = 2/N and allowing N to grow with T, requiring T = N^2. FedAsync removes its residual term by requiring the minimum number of local updates per client, H_min, to grow with T at rate H_min = T^{1/5}. While mathematically valid, the FedAsync condition places the asymptotic burden on ever-longer local training, which is less practical for resource-constrained cross-device FL. MR.AsyncFL's scaling assumption is better matched to large, dynamic cross-device federated learning settings.
"""

PAPER_EXPERIMENTS = """
SECTION 5: EXPERIMENTS

5.1 Experimental Setup

Datasets: CIFAR-10 and CIFAR-100.
- CIFAR-10: 60,000 color images (32x32 pixels), 10 classes, 50,000 training / 10,000 test.
- CIFAR-100: Same image size and total samples, but 100 classes with 600 images per class (500 training, 100 test). More challenging due to larger label space and higher inter-class similarity.

FL Setting: N = 30 clients.

Data Distribution:
- IID: Training data randomly shuffled and equally partitioned among all clients, ensuring each client receives a balanced mixture of all classes.
- Non-IID: Dirichlet distribution-based partitioning (concentration parameter = 0.5), which creates moderate statistical heterogeneity across clients.

Experimental Scenarios (4 total, for each dataset):
1. IID data, no staleness threshold
2. IID data, staleness threshold = 20
3. Non-IID data, staleness threshold = 20
4. Non-IID data, no staleness threshold

The no-threshold setting is a harsher empirical stress-test where algorithms must cope with arbitrary highly stale updates. The bounded-staleness setting reflects common practical AFL deployments.

5.2 Model Setup

Model architecture: ResNet18 (follows design from prior work).
- Initial conv layer with 64 channels, batch normalization, ReLU activation
- Four sequential residual layers with channel sizes 64, 128, 256, 512
- Global average pooling and fully connected output layer
- Identity or projection shortcuts in residual blocks

Framework: PyTorch
Hardware: Nvidia Titan V, RTX 3060, RTX 4090 GPUs, Ubuntu 24.04

5.3 Baselines

FedAsync: Immediate global model update upon receiving any client's local model, combining previous global model and new local model using a fixed or staleness-adjusted step size.
    w_t^g = (1-alpha_t) * w_{t-1}^g + alpha_t * w_t^(i)
where alpha_t = alpha * (delta_t + 1)^{-a}. Best hyperparameters: alpha=0.1, a=0.5.

TWAFL: Rolling average approach - at each global update, takes the weighted average of every client's latest local model, with weights based on staleness. Generalizes Rolling FedAvg by accounting for client staleness. Best decay coefficients: 0.5 (IID no threshold), 0.6 (IID with threshold), 0.4 (non-IID settings).

Rolling FedAvg: Staleness-agnostic version of TWAFL that aggregates the latest model from every client using uniform (or sample-size based) weights, without any adjustment for staleness.

5.4 Results and Analysis

MR.AsyncFL best gamma: gamma = 0.8 (IID, no threshold). Performance consistently improves as gamma increases, qualitatively aligned with theory (gamma -> 1 as T increases).

CIFAR-10 Results (Final Accuracy, Mean ± Std over 3 seeds):

              | No Stale Thres (IID) | Stale Thres=20 (IID) | No Stale Thres (Non-IID) | Stale Thres=20 (Non-IID)
MR.AsyncFL   |   80.77 ± 2.33      |    83.17 ± 1.21      |      77.88 ± 1.23        |      78.68 ± 0.98
FedAsync     |   75.28 ± 2.29      |    77.35 ± 2.87      |      71.13 ± 2.48        |      72.10 ± 2.72
TWAFL        |   79.19 ± 2.57      |    81.33 ± 1.90      |      73.16 ± 1.25        |      76.62 ± 1.54
Rolling FedAvg|  53.70 ± 2.39      |    53.70 ± 2.39      |      48.68 ± 2.09        |      48.68 ± 2.09

CIFAR-100 Results (Final Accuracy, 4000 FL epochs):

              | No Stale Thres (IID) | Stale Thres=20 (IID) | No Stale Thres (Non-IID) | Stale Thres=20 (Non-IID)
MR.AsyncFL   |   66.46 ± 1.81      |    68.19 ± 2.42      |      63.96 ± 1.39        |      65.19 ± 1.55
FedAsync     |   65.14 ± 1.84      |    65.88 ± 1.90      |      62.13 ± 2.02        |      63.36 ± 1.86
TWAFL        |   65.33 ± 1.90      |    67.63 ± 2.20      |      61.81 ± 1.80        |      63.71 ± 1.90
Rolling FedAvg|  40.22 ± 2.20      |    40.22 ± 2.15      |      38.48 ± 2.20        |      38.48 ± 2.15

Key Observations:
1. MR.AsyncFL achieves highest global accuracy in all 8 settings across both datasets.
2. The staleness threshold universally improves accuracy and convergence stability for all methods, without altering their relative ranking.
3. Non-IID data reduces accuracy and increases sensitivity to hyperparameters.
4. Rolling FedAvg performs worst across all scenarios, confirming the necessity of staleness-aware aggregation.
5. TWAFL shows a particularly large performance drop under non-IID settings when the staleness threshold is removed, due to its temporally weighted aggregation mechanism interacting badly with distribution-skewed stale models.
6. MR.AsyncFL advantages are particularly clear in challenging heterogeneous settings.

SECTION 6: CONCLUSION

MR.AsyncFL proposes a stale-model replacement mechanism: when a client uploads a new local model, the server replaces that client's previously cached local model in the server-side mixture with the new one, forming an adjusted intermediate model. It then combines this intermediate model with the same newly uploaded local model to produce the next global model.

Key technical contributions:
1. Stale-model replacement aggregation rule that explicitly removes outdated information
2. Recursive participation-weight scheme preserving normalization without auxiliary buffers
3. Convergence guarantee: O(T^{-1/4}) rate under bounded staleness
4. Consistently best accuracy across CIFAR-10 and CIFAR-100 in IID and non-IID settings
"""

# Organized chunks for RAG - each chunk is a meaningful unit
RAG_CHUNKS = [
    {
        "id": "abstract",
        "section": "Abstract",
        "content": PAPER_ABSTRACT.strip()
    },
    {
        "id": "intro_motivation",
        "section": "Introduction - Motivation",
        "content": """Federated learning (FL) trains machine learning models collaboratively across distributed clients while keeping raw data local. By exchanging only model updates instead of raw data, FL mitigates privacy leakage and reduces communication burden. This approach is used in healthcare, autonomous driving, IoT, and smart city contexts.

In synchronous FL (SFL) like FedAvg, the server waits for ALL selected clients before aggregation. This creates straggler problems: slower clients delay the entire training cycle, faster clients remain idle, and overall speed is constrained by the slowest participant.

Asynchronous federated learning (AFL) eliminates strict synchronization: the server updates the global model upon receiving EACH client update immediately, preventing stragglers from blocking progress."""
    },
    {
        "id": "intro_staleness_problem",
        "section": "Introduction - Staleness Problem",
        "content": """The fundamental challenge in AFL is staleness. Because local training and global aggregation occur independently, slow clients may have trained using an outdated global model that has been updated many times by faster clients. The server receives updates computed from stale models.

Aggregating stale gradients can destabilize training, introduce inconsistent model updates, and degrade final accuracy.

Trade-off: Fully AFL speeds up convergence by immediately incorporating updates but increases staleness. SFL eliminates staleness by waiting for all clients but at the cost of lower resource utilization and longer training time.

Existing AFL methods (FedAsync, TWAFL, WKAFL) typically address staleness by down-weighting stale updates through temporal decay or staleness-aware weighting. However, this only attenuates the influence of outdated information — stale client contributions can persist in the global model over time."""
    },
    {
        "id": "intro_contributions",
        "section": "Introduction - Contributions",
        "content": """MR.AsyncFL Contributions:
1. Novel AFL framework with stale-model substitution paradigm: each newly uploaded local model is used in two ways - (a) replaces the same client's previously cached stale contribution, and (b) participates in the aggregation step for the next global model. This reduces the lingering effect of outdated information.

2. Recursive weight normalization scheme: dynamically adjusts each client's contribution based on update delay and participation history. Maintains normalization without additional buffers or optimizer-specific modifications.

3. Convergence guarantee: O(T^{-1/4}) convergence rate under bounded staleness.

4. Extensive experiments on CIFAR-10 and CIFAR-100 under IID and non-IID settings, with and without staleness thresholds, consistently outperforming FedAsync, TWAFL, and Rolling FedAvg."""
    },
    {
        "id": "related_work_weighting",
        "section": "Related Work - Weight Aggregation Methods",
        "content": """Staleness-Aware AFL via Weight Aggregation:

FedAsync: Immediate aggregation upon client arrival. Applies staleness-aware hyperparameter during aggregation. The update is: w_t^g = gamma * w_{t-1}^g + (1-gamma) * w_t^(i). Treatment of staleness is coarse - stale updates are only softened through weighting, not removed.

TWAFL: Time-decay functions with exponential decay in aggregation update rule.

WKAFL: Two-stage K-async design with gradient clipping, staleness-aware learning rate, exponential weighting, and momentum. Added algorithmic complexity reduces practicality.

FedACA: "Informative update" policy - client sends updates only when model has changed significantly. Server weights update by a time-related factor.

TimelyFL: Fairness through wall-clock time control and adaptive workload assignment. Focuses on participation fairness, not staleness correction.

All these methods remain within a weighted-aggregation framework where stale information is moderated rather than explicitly replaced."""
    },
    {
        "id": "algorithm_problem_setup",
        "section": "Algorithm - Problem Setup",
        "content": """Problem Setup for MR.AsyncFL:

System: Central server + N clients indexed by i in {1,...,N}.
Each client i: private dataset of size n_i from distribution D_i. Data never shared.
Server: maintains global model w in R^d.

Global objective: minimize F(w) = sum_{i=1}^{N} r_i * F_i(w)
where r_i = n_i / sum_j n_j (relative data size of client i)
F_i(w) = E_{zeta~D_i}[f(w; zeta)] (expected local loss)
f(w, zeta) is the loss function for model w on sample zeta."""
    },
    {
        "id": "algorithm_protocol",
        "section": "Algorithm - Communication Protocol",
        "content": """MR.AsyncFL Communication Protocol:

1. SYSTEM INITIATION: Server broadcasts initial global model w_0^g to selected clients.

2. CLIENT UPDATE: Client i performs local training using SGD:
   w_t^(i) = w_{t-delta_t-1}^g - eta * g_t
   where delta_t >= 0 is staleness (how many rounds behind).
   Critical: the client trained from w_{t-delta_t-1}^g, not the latest global model.

3. MODEL EXCHANGE (pre-aggregation design): Upon receiving client i's model, server broadcasts its latest global model w_{t-1}^g to client i BEFORE executing aggregation. This speeds up the next local training cycle.

4. SERVER AGGREGATION: Server integrates w_t^(i) into global model using MR.AsyncFL update rule.

Bounded staleness: delta_t <= tau. If a client hasn't uploaded for more than tau rounds, server resets its training by sending the most recent global model. This limits adverse effects of severely outdated models."""
    },
    {
        "id": "algorithm_update_rule",
        "section": "Algorithm - Update Equation",
        "content": """MR.AsyncFL Update Equation:

Global model as mixture: w_{t-1}^g = sum_{j=1}^{N} c_{t-1}^(j) * w_{t-1}^(j)
where c_{t-1}^(j) are weights (sum to 1), w_{t-1}^(j) is the most recent cached model from client j.

Stale-model replacement:
    w_tilde_{t-1}^g = w_{t-1}^g - c_{t-1}^(i) * w_{t-delta_t}^(i) + c_{t-1}^(i) * w_t^(i)

MR.AsyncFL update:
    w_t^g = gamma * w_tilde_{t-1}^g + (1-gamma) * w_t^(i)
          = gamma * w_{t-1}^g + (1-gamma) * w_t^(i) + gamma * c_{t-1}^(i) * (w_t^(i) - w_{t-delta_t}^(i))
          = sum_{j!=i} gamma*c_{t-1}^(j)*w_{t-1}^(j) + (gamma*c_{t-1}^(i) + 1-gamma) * w_t^(i)

The extra term gamma * c_{t-1}^(i) * (w_t^(i) - w_{t-delta_t}^(i)) is the key difference from FedAsync.
This term fully removes the old stale contribution of client i.

FedAsync comparison: FedAsync update leaves gamma * c_{t-1}^(i) * w_{t-delta_t}^(i) (stale contribution) in the model.
MR.AsyncFL explicitly removes it by adding the model difference term."""
    },
    {
        "id": "algorithm_weight_update",
        "section": "Algorithm - Recursive Weight Update",
        "content": """Recursive Weight Update Rule:

After incorporating w_t^(i), the global model is still a weighted combination:
    w_t^g = sum_{j=1}^{N} c_t^(j) * w_t^(j)

Weight update recurrence:
    c_t^(j) = gamma * c_{t-1}^(j),                 for j != i (non-participating)
    c_t^(i) = gamma * c_{t-1}^(i) + (1-gamma),     for j = i  (participating)

Initial values: c_0^(j) = 1/N for all j.

Interpretation:
- Non-participating clients: importance discounted by gamma (one step staler)
- Participating client i: discounted by gamma but gets bonus (1-gamma) for recency

Normalization preservation: Given sum_j c_{t-1}^(j) = 1:
    sum_j c_t^(j) = gamma * sum_j c_{t-1}^(j) + (1-gamma) = gamma*1 + (1-gamma) = 1

This guarantees the global model remains a convex combination of cached client models, preventing unintended scaling effects.

Memory requirement: Server must store the most recently uploaded model from each client. This enables precise staleness compensation without requiring clients to re-send old models.

Memory reduction techniques: compressed (low-precision) models, client clustering into representative groups."""
    },
    {
        "id": "convergence_assumptions",
        "section": "Convergence - Assumptions",
        "content": """Convergence Assumptions for MR.AsyncFL:

Assumption 1 (Objective Properties): F: R^d -> R is bounded from below (F(w) >= F* for all w) and L-smooth: ||nabla F(u) - nabla F(v)|| <= L * ||u-v|| for all u,v.

Assumption 2 (Stochastic Gradient): Client update satisfies g_t = nabla F_i(w^g_{t-delta_t-1}) + xi_t where E[xi_t | F_{t-1}] = 0 (unbiased noise).

Assumption 3 (Bounded Staleness): delta_t <= tau where tau > 0 is a finite positive integer.

Assumption 4 (Participation Probability): r_i = E[1_t^i] <= r for all i, t, where r in [1/N, 1) is the maximum participation probability. This is used to bound client weights.

Assumption 5 (Bounded Local Update): ||g_t|| <= G for any client and t.

Assumption 6 (rho condition): rho := 4 * tau^2 * [(1-gamma)^2 + gamma^2 * r] < 1. This ensures a contraction property (similar condition appears in FedAsync analysis)."""
    },
    {
        "id": "convergence_theorem",
        "section": "Convergence - Main Theorem",
        "content": """Convergence Theorem for MR.AsyncFL:

Under Assumptions 1-6:
    min_{t=1,...,T} E[||nabla F(w_{t-1}^g)||^2]
    <= (4/(1-gamma)) * (
          (F(w_0^g) - F*) / (eta*T)
          + C_w * [(1-gamma + 2*gamma*r)/2 + eta^2*L^2]
          + gamma*r*G^2
          + L*C_Delta*eta
       )

where C_Delta = 4*G^2 * [(1-gamma)^2 + 2*gamma*r] / (1-rho)
and C_w = tau^2 * C_Delta.

O(T^{-1/4}) Rate: By choosing eta = 1/sqrt(T), r = 2/N, gamma = 1 - 1/T^{1/4}, T = N^2:
    min_{t=1,...,T} E[||nabla F(w_{t-1}^g)||^2] = O(T^{-1/4})

Physical meaning: With 30 clients (N=30), set T = 900 rounds, r = 2/30 ≈ 0.067, gamma ≈ 1 - 1/900^{0.25} ≈ 0.822.

Key insight: The residual error floor vanishes by increasing N with T (T = N^2). This is natural in open cross-device FL where new clients may join over time. Unlike FedAsync which requires growing H_min (local computation per client), MR.AsyncFL's scaling condition is better suited for resource-constrained edge devices."""
    },
    {
        "id": "experiments_setup",
        "section": "Experiments - Setup",
        "content": """Experimental Setup:

Datasets: CIFAR-10 (10 classes), CIFAR-100 (100 classes), both with 32x32 color images.

FL setup: N = 30 clients.

IID: Training data randomly shuffled and equally partitioned.
Non-IID: Dirichlet distribution with concentration parameter 0.5 (moderate heterogeneity).

Four scenarios per dataset:
1. IID, no staleness threshold (harsh stress-test)
2. IID, staleness threshold = 20
3. Non-IID, staleness threshold = 20
4. Non-IID, no staleness threshold

Training: 1000 FL epochs for CIFAR-10, 4000 epochs for CIFAR-100.
Model: ResNet18.
Hardware: Nvidia Titan V, RTX 3060, RTX 4090.
Reported: Mean ± std over 3 seeds (randomness from asynchronous client participation order).

Baselines and best hyperparameters:
- FedAsync: alpha=0.1, a=0.5 (staleness-aware variant)
- TWAFL: decay=0.5 (IID no thresh), 0.6 (IID with thresh), 0.4 (non-IID settings)
- Rolling FedAvg: no staleness parameters
- MR.AsyncFL: gamma=0.8 (optimal, consistent across settings)"""
    },
    {
        "id": "experiments_results",
        "section": "Experiments - Results",
        "content": """Experimental Results:

CIFAR-10 Final Accuracy (Mean ± Std, 3 seeds):

IID, No Staleness Threshold:
- MR.AsyncFL: 80.77 ± 2.33% (BEST)
- TWAFL:      79.19 ± 2.57%
- FedAsync:   75.28 ± 2.29%
- Rolling FedAvg: 53.70 ± 2.39%

IID, Staleness Threshold = 20:
- MR.AsyncFL: 83.17 ± 1.21% (BEST)
- TWAFL:      81.33 ± 1.90%
- FedAsync:   77.35 ± 2.87%
- Rolling FedAvg: 53.70 ± 2.39%

Non-IID, No Staleness Threshold:
- MR.AsyncFL: 77.88 ± 1.23% (BEST)
- FedAsync:   71.13 ± 2.48%
- TWAFL:      73.16 ± 1.25%
- Rolling FedAvg: 48.68 ± 2.09%

Non-IID, Staleness Threshold = 20:
- MR.AsyncFL: 78.68 ± 0.98% (BEST)
- TWAFL:      76.62 ± 1.54%
- FedAsync:   72.10 ± 2.72%
- Rolling FedAvg: 48.68 ± 2.09%

CIFAR-100 Final Accuracy (4000 epochs):
- MR.AsyncFL consistently best: 66.46%, 68.19%, 63.96%, 65.19% across the 4 settings
- Rolling FedAvg consistently worst: ~38-40%

Key findings:
1. MR.AsyncFL is best in all 8 experimental settings
2. Staleness threshold improves all methods; doesn't change relative ranking
3. Non-IID is harder than IID for all methods
4. TWAFL shows larger drop under non-IID + no threshold (temporally weighted aggregation interacts badly with distribution-skewed stale models)
5. Rolling FedAvg's poor performance validates the necessity of staleness-aware aggregation"""
    },
]

def get_all_chunks():
    """Return all paper chunks as a list of dicts with id, section, content."""
    return RAG_CHUNKS

def get_full_text():
    """Return full paper text as a single string."""
    return "\n\n".join([
        PAPER_TITLE,
        PAPER_ABSTRACT,
        PAPER_INTRODUCTION,
        PAPER_RELATED_WORK,
        PAPER_ALGORITHM,
        PAPER_CONVERGENCE,
        PAPER_EXPERIMENTS
    ])
